all:
	module unload openmpi4; module load nvhpc; \
	pgcc -o lake lake.c -I./ -acc -gpu,time -fast -Minfo=accel -Minline -Msafeptr -Mnodepchk -lm; \
	module unload nvhpc; module load openmpi4

clean:
	rm -f *.o *~ *.dat *.png lake.log lake
